Repository JNU-econovation/Let-s-git-it-started, pull requests merged in 2023-11, with the labels that each got.

#66 docs: update exercise.md
  1st_Let_s_git_it_started(Git_tutorial)/exercise.md
Labels: guide

#57 이도연(capDoYeonLee) - 자기소개
  2023-2/tony.md
Labels: 23기, 자기소개, ENFJ

#61 조배경(baegyeong) - 자기소개
  2023-2/baegyeong.md
Labels: 23기, 자기소개, ISFJ

#62 임수미(LimSumi) - 자기소개
  2023-2/LimSumi.md
Labels: 24기, 자기소개, ISTP, INTP

#63 김건형(fusillading) - 자기소개
  2023-2/fusillading.md
Labels: 24기, 자기소개, ENTP

#64 김동완(dxwwan) - 자기소개
  1st_Let_s_git_it_started(Git_tutorial)/guide.md
  2023-2/dxwwan.md
Labels: 25기, 자기소개, ISTP, ESTP

#69 박영규(pyg410) - 자기소개
  2023-2/cookie.md
Labels: 24기, 자기소개, INFP

#71 김종준(belljun3395) - 자기소개
  2023-2/jongjun.md
Labels: 23기, 자기소개, ISTJ

#72 박준수(Joonsu25) - 자기소개
  2023-2/Joonsu25.md
Labels: 25기, 자기소개, INFJ

#73 이진혁(LJH098) - 자기소개
  2023-2/jinhyuk.md
Labels: 25기, 자기소개, ENTP

#74 김종민(rlajm1203) - 자기소개
  2023-2/Kimjongmin.md
Labels: 자기소개, ENTJ, 26기

#75 박경준(Kyeong6) - 자기소개
  2023-2/박경준.md
Labels: 25기, 자기소개, ISTJ

#76 강바다(bada308) - 자기소개
  2023-2/bada308.md
Labels: 25기, 자기소개, ISFP

#77 박민규(ps9319) - 자기소개
  2023-2/ps9319.md
Labels: 자기소개, ISFP, 26기

#78 곽민준(mlnwns) - 자기소개
  2023-2/mlnwns.md
Labels: 자기소개, INTJ, 26기

#79 김채원(chaewon215) - 자기소개
  2023-2/chaewon.md
Labels: 25기, 자기소개, ENTP

#80 곽민주(MinjuKwak01) - 자기소개
  2023-2/kwakminju.md
Labels: 자기소개, ISFP, 26기

#81 박현솔(kyeonsol) - 자기소개
  2023-2/kyeonsol.md
Labels: 자기소개, ENTP, 26기

#82 윤석호(inferior3x) - 자기소개
  2023-2/inferior3x.md
Labels: 자기소개, ISTJ, 26기

#83 박지유(jiucchu) - 자기소개
  2023-2/박지유.md
Labels: 25기, 자기소개, ENTJ

#84 장홍준(ajang369) - 자기소개
  2023-2/hongjun.md
Labels: 25기, 자기소개, ISFJ

#85 이장안(lja3723) - 자기소개
  2023-2/lja3723.md
Labels: 자기소개, INTP, 26기

#86 오명헌(myeongheonn)-자기소개
  2023-2/오명헌.md
Labels: 자기소개, ENFJ, 26기

#87 정서윤(yunn23) - 자기소개
  2023-2/yunn23.md
Labels: 자기소개, ISFP, 26기

#88 박건규(geongyu09) - 자기소개
  2023-2/geongyu09.md
Labels: 자기소개, INTJ, 26기

#89 최규민(gyuminzzz) - 자기소개
  2023-2/gyumin.md
Labels: 자기소개, ESTJ, 26기

#90 강하은(@kanghaeun)-자기소개
  2023-2/kanghaeun.md
Labels: 자기소개, ISTJ, 26기

#91 김성빈(saine0501) - 자기소개
  2023-2/김성빈.md
Labels: 자기소개, ISTP, 26기

#92 서영우(westzeroright)-자기소개
  2023-2/서영우.md
Labels: 자기소개, INFP, 26기

#93 김근성(rootachieve) - 자기소개
  2023-2/김근성.md
Labels: 25기, 자기소개, INFJ

#94 장현지(Hyeonz1) - 자기소개
  2023-2/Hyeonz1.md
Labels: 24기, 자기소개, ISFP
