Repository JNU-econovation/Let-s-git-it-started, pull requests merged in 2024-04, with the labels that each got.

#108 update: 2024년 1학기 Let's git it started 행사에 맞게 수정
  1st_Let_s_git_it_started(Git_tutorial)/quick_guide.md
Labels: 27기

#109 [DOCS] 2024-1 디렉터리 README.md 작성
  1st_Let_s_git_it_started(Git_tutorial)/2024-1/README.md
Labels: 26기

#110 [UPDATE] README.md 수정
  1st_Let_s_git_it_started(Git_tutorial)/2024-1/README.md
Labels: 26기

#140 정인재(injae-348) - 자기소개
  1st_Let_s_git_it_started(Git_tutorial)/2024-1/JeongInJae_profile.md
Labels: 자기소개, ISFJ, 27기

#112 박민규(ps9319) - 자기 소개
  1st_Let_s_git_it_started(Git_tutorial)/2024-1/ParkMinKyu_profile.md
Labels: 자기소개, ISFP, 26기

#115 이진혁(LJH098) - 자기소개
  1st_Let_s_git_it_started(Git_tutorial)/2024-1/LeeJinHyuk.md
Labels: 25기, 자기소개, ENTP

#117 최규민(gyuminzzz) - 자기소개
  1st_Let_s_git_it_started(Git_tutorial)/2024-1/ChoiGyuMin_profile.md
Labels: 자기소개, ESTJ, 26기

#118 김수민(mando) - 자기소개
  1st_Let_s_git_it_started(Git_tutorial)/2024-1/KimSuMin_profile.md
Labels: 22기, 자기소개, ISTP

#119 윤석호(inferior3x) - 자기소개
  1st_Let_s_git_it_started(Git_tutorial)/2024-1/YoonSeokHo_profile.md
Labels: 자기소개, ISTJ, 26기

#122 곽민준(mlnwns) - 자기소개
  1st_Let_s_git_it_started(Git_tutorial)/2024-1/mlnwns.md
Labels: 자기소개, INTJ, 26기

#124 강하은(kanghaeun) - 자기소개
  1st_Let_s_git_it_started(Git_tutorial)/2024-1/haeun.md
Labels: 자기소개, ISTJ, 26기

#125 박준수(Joonsu25) - 자기소개
  1st_Let_s_git_it_started(Git_tutorial)/2024-1/Steve.md
Labels: 25기, 자기소개, INFJ

#126 서영우(westzeroright) - 자기소개
  1st_Let_s_git_it_started(Git_tutorial)/2024-1/SeoYeongU_profile.md
Labels: 자기소개, INFP, 26기

#127 곽민주(MinjuKwak01) - 자기소개
  1st_Let_s_git_it_started(Git_tutorial)/2024-1/KwakMinju_profile.md
Labels: 자기소개, ISFP, 26기

#128 박지유(jiucchu) - 자기소개
  1st_Let_s_git_it_started(Git_tutorial)/2024-1/jiucchu.md
Labels: 25기, 자기소개, ENTJ

#129 조인식(ChoInSik) - 자기소개
  1st_Let_s_git_it_started(Git_tutorial)/2024-1/ChoInSik_profile.md
Labels: 자기소개, ESFP, 27기

#131 이다현(leedahyeon)-자기소개
  1st_Let_s_git_it_started(Git_tutorial)/2024-1/Leedahyeon.md
Labels: 자기소개, ESFJ, 27기

#132 정수인(suuuin)-자기소개
  1st_Let_s_git_it_started(Git_tutorial)/2024-1/suuuin.md
Labels: 25기, 자기소개, INFP

#133 김근성(rootachieve) - 자기소개
  1st_Let_s_git_it_started(Git_tutorial)/2024-1/kimgeunseong_profile.md
Labels: 25기, 자기소개, INFJ

#134 노을(yes-eul) - 자기소개
  1st_Let_s_git_it_started(Git_tutorial)/2024-1/Eul_Noh.md
Labels: 자기소개, ESTJ, 27기

#135 김성빈(saine0501) - 자기소개
  1st_Let_s_git_it_started(Git_tutorial)/2024-1/KimSeongBin_profile.md
Labels: 자기소개, ISTP, 26기

#137 백경환(BaekGyeongHwan)-자기소개
  1st_Let_s_git_it_started(Git_tutorial)/2024-1/BaekGyeongHwan_profile.md
Labels: 자기소개, ISFJ, 27기

#138 김채원(chaewon215) - 자기소개
  1st_Let_s_git_it_started(Git_tutorial)/2024-1/chaewon.md
Labels: 25기, 자기소개, ENTP

#139 오명헌(myeongheonn) - 자기소개
  1st_Let_s_git_it_started(Git_tutorial)/2024-1/OhMyeongHeon_profile.md
Labels: 자기소개, ENFJ, 26기

#141 강명덕(Profile-exe) - 자기소개
  1st_Let_s_git_it_started(Git_tutorial)/2024-1/kang_myeong_deok.md
Labels: 자기소개, ISTP, 27기

#142 박건규 (geongyu09)-자기소개 🍩
  1st_Let_s_git_it_started(Git_tutorial)/2024-1/_donut_gyu.md
Labels: 자기소개, ISFJ, 26기

#145 김가현(kghe9308)-자기소개
  1st_Let_s_git_it_started(Git_tutorial)/2024-1/KimGaHyeon.md
Labels: INTP, 27기

#146 정승현(221186) - 자기소개
  1st_Let_s_git_it_started(Git_tutorial)/2024-1/JungSeungHyen_profile.md
Labels: 자기소개, 27기

#121 김동완(dxwwan) - 자기소개
  1st_Let_s_git_it_started(Git_tutorial)/2024-1/dxwwan_profile.md
Labels: 25기, 자기소개, ESTP

#147 김다애(Daae-Kim) 자기소개 🦴
  1st_Let_s_git_it_started(Git_tutorial)/2024-1/daae.md
Labels: 20기, 자기소개, INTP
